image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - tag

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

tag latest:
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

## Aditional build jobs for special-flavor Dockerfiles
## ----

.build special:
  stage: build
  variables:
    BUILD_DOCKERFILE: Dockerfile
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_FLAVOR || true
    - docker build
      --build-arg BUILD_FROM=${BUILD_FROM}
      --tag $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA
      --file ${BUILD_DOCKERFILE} .
    - docker run --rm $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA uname -m
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA

.tag special:
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}
  only:
    - master

build armv7:  {extends: .build special, variables: {IMAGE_FLAVOR: armv7, BUILD_FROM: "arm32v7/python:3.6-alpine"}}
tag armv7:    {extends: .tag special,   variables: {IMAGE_FLAVOR: armv7}}
