variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - tag

.tox:
  # Define a default image here, used also by docs, coverage jobs
  image: python:3.7
  stage: test
  before_script:
    - pip install tox
  script:
    - tox -e ${CI_JOB_NAME}

docs:
  extends: .tox

coverage:
  extends: .tox

py27:
  extends: .tox
  image: python:2.7
  script: tox -e py27

py34:
  extends: .tox
  image: python:3.4

py35:
  extends: .tox
  image: python:3.5

py36:
  extends: .tox
  image: python:3.6

py37:
  extends: .tox
  image: python:3.7

py38:
  extends: .tox
  image: python:3.8.0rc1

.docker:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  extends: .docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

tag latest:
  extends: .docker
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

## Aditional build jobs for special-flavor Dockerfiles
## ----

.build special:
  extends: .docker
  variables:
    BUILD_DOCKERFILE: Dockerfile
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_FLAVOR || true
    - docker build
      --build-arg BUILD_FROM=${BUILD_FROM}
      --tag $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA
      --file ${BUILD_DOCKERFILE} .
    - docker run --rm $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA uname -m
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA

.tag special:
  extends: .docker
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_FLAVOR}
  only:
    - master

build armv7:
  extends: .build special
  variables: { IMAGE_FLAVOR: armv7, BUILD_FROM: "arm32v7/python:3.6-alpine" }

tag armv7:
  extends: .tag special
  variables: { IMAGE_FLAVOR: armv7 }
